# Site settings
name: AREA 2020 Workshop
email:
author: Rafael C. Cardoso, Angelo Ferrando, Tobias Ahlbrecht, Claudio Menghi, Daniela Briola

keywords: autonomous systems, robotics, artificial intelligence, formal verification, sensor systems, programming, formal modelling, software engineering
description: The First Workshop on Agents and Robots for reliable Engineered Autonomy (AREA 2020)

# Only use this if you are serving your site via Github Pages
#github:

#url:  "http://localhost:4000"
#images: "http://localhost:4000/images/"

url: "https://area2020.github.io/"
images: "https://area2020.github.io/images/"


header: no
header_sm: images/ashton-small.png
header_med: images/ashton-med.png
header_large: images/ashton-large.png
header_xl: images/ashton-xl-desat.png

include: [_events]

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

collections:
  events:
    output: true
  projects:
    output: false
  projects-previous:
    output: false
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

address:
  - line: University of Liverpool Ashton Building Ashton Street Liverpool L69 3BX United Kingdom

#Google API key
google_api_key: AIzaSyB1miEwJXVP4HydUImEL5ONmzvCL37_dBU

#### SEO Stuff

# Twitter Cards
twitter_user: AREA2020
twitter_card: true
twitter_image: https://area2020.github.io/images/logos/area_logo_1.png    #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Usernames for things
researchgate_username: AREA2020

# URLS
UoL_URL: https://www.liverpool.ac.uk/computer-science/
UoY_URL: https://www.cs.york.ac.uk/
AA_URL: https://www.york.ac.uk/assuring-autonomy/
ONR_URL: http://www.onr.org.uk/
NCNR_HUB_URL: https://www.ncnr.org.uk/
RAIN_HUB_URL: https://rainhub.org.uk/
VV_NETWORK_URL: https://vavas.org/
